apiVersion: batch/v1
kind: CronJob
metadata:
  name: catalog-backup
  namespace: catalog
  labels:
    app.kubernetes.io/name: catalog-backup
    app.kubernetes.io/created-by: eks-workshop
spec:
  schedule: "0 2 * * *"  # Every day at 2 AM
  timeZone: "UTC"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: catalog-backup
        spec:
          restartPolicy: OnFailure
          containers:
          - name: backup
            image: mysql:8.0
            command:
            - /bin/bash
            - -c
            - |
              echo "Starting backup at $(date)"
              mysqldump -h catalog-mysql -u root -pmy-secret-pw catalog > /backup/catalog-$(date +%Y%m%d).sql
              echo "Backup completed at $(date)"
              ls -la /backup/
            volumeMounts:
            - name: backup-storage
              mountPath: /backup
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                cpu: 200m
                memory: 256Mi
          volumes:
          - name: backup-storage
            emptyDir: {}