apiVersion: v1
kind: Pod
metadata:
  name: catalog-pod
  namespace: catalog
  labels:
    app.kubernetes.io/name: catalog
    app.kubernetes.io/component: service
    app.kubernetes.io/created-by: eks-workshop
spec:
  containers:
  - name: catalog
    image: public.ecr.aws/aws-containers/retail-store-sample-catalog:0.4.0
    ports:
    - containerPort: 8080
    env:
    - name: DB_USERNAME
      valueFrom:
        secretKeyRef:
          name: catalog-db
          key: RETAIL_CATALOG_PERSISTENCE_USER
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: catalog-db
          key: RETAIL_CATALOG_PERSISTENCE_PASSWORD
    - name: DB_ENDPOINT
      value: "catalog-mysql:3306"
    - name: DB_NAME
      value: "catalog"
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "200m"